INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('BOB', 200.0);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('MARIA', 300.0);
INSERT INTO TB_WORKER (NAME, DAILY_INCOME) VALUES ('ALEX', 250.0);